image: selenium/standalone-chrome:3.1.0

pipelines:
  default:
    - step:
        script:
          # run selenium in the background
          - /opt/bin/entry_point.sh &
          # install curl and git
          - sudo apt-get update
          - sudo apt-get install -y curl git
          # install node and npm
          - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
          - sudo apt-get install -y nodejs
          - sudo npm install -g npm@latest
          # install app dependency
          - npm install
          - npm run lint
          - npm run build
          - npm run test:unit
          # upload code to sandbox
          - npm run upload -- -H $SANDBOX_HOSTNAME -u $SANDBOX_USERNAME -p $SANDBOX_PASSWORD --cartridge app_storefront_controllers,app_storefront_core,app_storefront_pipelines --code-version $SANDBOX_CODE_VERSION
          # run test
          - npm run test:application -- --url $SITE_URL
